server:
  port: 8085
  tomcat:
    threads:
      max: 100

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/payment_db
    username: ${DB_USER:railway}
    password: ${DB_PASSWORD:railway}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

management:
  endpoints.web.exposure.include: health,info,prometheus
